// Micronutrient targets (adult daily, approx) + units. Amounts everywhere are in these units.
export const MICROS = [
  { key: 'fiber', label: 'Fiber', unit: 'g', target: 30 },
  { key: 'sugar', label: 'Sugars', unit: 'g', target: 50, over: true },
  { key: 'satfat', label: 'Sat. fat', unit: 'g', target: 20, over: true },
  { key: 'sodium', label: 'Sodium', unit: 'mg', target: 2300, over: true },
  { key: 'calcium', label: 'Calcium', unit: 'mg', target: 1000 },
  { key: 'iron', label: 'Iron', unit: 'mg', target: 18 },
  { key: 'potassium', label: 'Potassium', unit: 'mg', target: 3500 },
  { key: 'magnesium', label: 'Magnesium', unit: 'mg', target: 400 },
  { key: 'zinc', label: 'Zinc', unit: 'mg', target: 11 },
  { key: 'vitc', label: 'Vitamin C', unit: 'mg', target: 80 },
  { key: 'vita', label: 'Vitamin A', unit: 'µg', target: 800 },
  { key: 'vitd', label: 'Vitamin D', unit: 'µg', target: 15 },
  { key: 'vitb12', label: 'Vitamin B12', unit: 'µg', target: 2.4 },
];

// Common Indian-market medicines. `supp` micros (in MICROS units) roll into the panel.
export const INDIAN_MEDS = [
  { name: 'Dolo 650', salt: 'Paracetamol 650mg' },
  { name: 'Crocin Advance', salt: 'Paracetamol 500mg' },
  { name: 'Calpol 500', salt: 'Paracetamol 500mg' },
  { name: 'Combiflam', salt: 'Ibuprofen + Paracetamol' },
  { name: 'Brufen 400', salt: 'Ibuprofen 400mg' },
  { name: 'Meftal Spas', salt: 'Mefenamic acid + Dicyclomine' },
  { name: 'Meftal P', salt: 'Mefenamic acid + Paracetamol' },
  { name: 'Disprin', salt: 'Aspirin 325mg' },
  { name: 'Aceclofenac Zerodol', salt: 'Aceclofenac 100mg' },
  { name: 'Zerodol P', salt: 'Aceclofenac + Paracetamol' },
  { name: 'Azithral 500', salt: 'Azithromycin 500mg' },
  { name: 'Azee 500', salt: 'Azithromycin 500mg' },
  { name: 'Augmentin 625', salt: 'Amoxicillin + Clavulanic acid' },
  { name: 'Mox 500', salt: 'Amoxicillin 500mg' },
  { name: 'Cifran 500', salt: 'Ciprofloxacin 500mg' },
  { name: 'Taxim-O 200', salt: 'Cefixime 200mg' },
  { name: 'Monocef', salt: 'Ceftriaxone' },
  { name: 'Metrogyl 400', salt: 'Metronidazole 400mg' },
  { name: 'Norflox TZ', salt: 'Norfloxacin + Tinidazole' },
  { name: 'Doxt-SL', salt: 'Doxycycline + Lactic acid bacillus' },
  { name: 'Pan 40', salt: 'Pantoprazole 40mg' },
  { name: 'Pan-D', salt: 'Pantoprazole + Domperidone' },
  { name: 'Pantop 40', salt: 'Pantoprazole 40mg' },
  { name: 'Omez', salt: 'Omeprazole 20mg' },
  { name: 'Rantac 150', salt: 'Ranitidine 150mg' },
  { name: 'Digene', salt: 'Antacid gel' },
  { name: 'Gelusil', salt: 'Antacid + Simethicone' },
  { name: 'Eno', salt: 'Sodium bicarbonate' },
  { name: 'Ondem 4', salt: 'Ondansetron 4mg' },
  { name: 'Vomikind 4', salt: 'Ondansetron 4mg' },
  { name: 'Domstal', salt: 'Domperidone 10mg' },
  { name: 'Cetzine', salt: 'Cetirizine 10mg' },
  { name: 'Allegra 120', salt: 'Fexofenadine 120mg' },
  { name: 'Montek LC', salt: 'Montelukast + Levocetirizine' },
  { name: 'Avil 25', salt: 'Pheniramine 25mg' },
  { name: 'Sinarest', salt: 'Paracetamol + Phenylephrine + CPM' },
  { name: 'Vicks Action 500', salt: 'Paracetamol + Phenylephrine + Caffeine' },
  { name: 'Cheston Cold', salt: 'Cetirizine + Paracetamol + Phenylephrine' },
  { name: 'Ascoril LS', salt: 'Ambroxol + Levosalbutamol + Guaifenesin' },
  { name: 'Grilinctus', salt: 'Cough syrup' },
  { name: 'Benadryl', salt: 'Diphenhydramine cough syrup' },
  { name: 'Corex', salt: 'Chlorpheniramine + Codeine' },
  { name: 'Otrivin', salt: 'Xylometazoline nasal' },
  { name: 'Betadine gargle', salt: 'Povidone iodine' },
  { name: 'Strepsils', salt: 'Amylmetacresol lozenge' },
  { name: 'ORS (Electral)', salt: 'Oral rehydration salts' },
  { name: 'Enterogermina', salt: 'Bacillus clausii probiotic' },
  { name: 'Econorm', salt: 'Saccharomyces boulardii' },
  { name: 'Sporlac', salt: 'Lactic acid bacillus' },
  { name: 'Cremaffin', salt: 'Laxative (milk of magnesia + liquid paraffin)' },
  { name: 'Dulcoflex', salt: 'Bisacodyl 5mg' },
  { name: 'Isabgol', salt: 'Psyllium husk', micros: { fiber: 3.5 } },
  { name: 'Volini gel', salt: 'Diclofenac topical' },
  { name: 'Moov', salt: 'Analgesic topical' },
  { name: 'Soframycin', salt: 'Framycetin skin cream' },
  { name: 'Betnovate', salt: 'Betamethasone cream' },
  { name: 'Candid', salt: 'Clotrimazole antifungal' },
  { name: 'Metformin (Glycomet)', salt: 'Metformin 500mg' },
  { name: 'Telma 40', salt: 'Telmisartan 40mg' },
  { name: 'Amlong 5', salt: 'Amlodipine 5mg' },
  { name: 'Ecosprin 75', salt: 'Aspirin 75mg' },
  { name: 'Atorva 10', salt: 'Atorvastatin 10mg' },
  { name: 'Thyronorm 50', salt: 'Levothyroxine 50mcg' },
  { name: 'Eltroxin 100', salt: 'Levothyroxine 100mcg' },
  // supplements — these feed the micronutrient panel
  { name: 'Shelcal 500', salt: 'Calcium + Vitamin D3', micros: { calcium: 500, vitd: 6.25 } },
  { name: 'Calcimax', salt: 'Calcium + Vitamin D3', micros: { calcium: 500, vitd: 5 } },
  { name: 'Uprise D3 60K', salt: 'Cholecalciferol 60000 IU', micros: { vitd: 1500 } },
  { name: 'Limcee', salt: 'Vitamin C 500mg', micros: { vitc: 500 } },
  { name: 'Celin 500', salt: 'Vitamin C 500mg', micros: { vitc: 500 } },
  { name: 'Zincovit', salt: 'Multivitamin + Zinc', micros: { zinc: 22.5, vitc: 75, vita: 600, vitb12: 1 } },
  { name: 'Supradyn', salt: 'Multivitamin multimineral', micros: { vitc: 150, zinc: 15, iron: 10, calcium: 100, vitb12: 15, vita: 800 } },
  { name: 'Revital H', salt: 'Multivitamin + Ginseng', micros: { vitc: 40, zinc: 15, vitb12: 1, calcium: 70, iron: 8 } },
  { name: 'Neurobion Forte', salt: 'Vitamin B-complex', micros: { vitb12: 15 } },
  { name: 'Becosules', salt: 'Vitamin B-complex + C', micros: { vitc: 75, vitb12: 15 } },
  { name: 'Autrin', salt: 'Iron + Folic acid + B12', micros: { iron: 150, vitb12: 15 } },
  { name: 'Livogen', salt: 'Iron + Folic acid', micros: { iron: 152 } },
  { name: 'Dexorange', salt: 'Iron + B12 syrup', micros: { iron: 100, vitb12: 7.5 } },
  { name: 'Ferium XT', salt: 'Iron + Folic acid', micros: { iron: 100 } },
  { name: 'A to Z NS', salt: 'Multivitamin', micros: { vitc: 75, zinc: 12, calcium: 100, iron: 8, vitb12: 5 } },
  { name: 'Cobadex CZS', salt: 'Multivitamin + Zinc + Chromium', micros: { zinc: 12, vitc: 75 } },
  { name: 'Ostocalcium', salt: 'Calcium + B12 + D', micros: { calcium: 250, vitb12: 1, vitd: 5 } },
];

// ---- supplement shelf ----
// The eight things people actually keep on a shelf, plus an escape hatch. Each
// carries a typical serving so one tap logs something real rather than a bare
// checkbox — the macros move the intake tiles and the micros roll into the
// micronutrient panel exactly like a scanned food does.
//
// These are label-panel typicals, not prescriptions: brands vary a lot, so every
// field stays editable on the entry after logging.
export const SUPPLEMENTS = [
  {
    key: 'whey', label: 'Protein', icon: 'whey', color: 'var(--red)',
    serving: '1 scoop (30g)', note: 'Whey concentrate/isolate',
    macros: { kcal: 120, protein: 24, carbs: 3, fat: 1.5 },
    micros: { calcium: 120 },
  },
  {
    key: 'creatine', label: 'Creatine', icon: 'creatine', color: 'var(--cyan)',
    serving: '5 g', note: 'Monohydrate, daily',
    macros: {}, micros: {},
  },
  {
    key: 'preworkout', label: 'Pre-Workout', icon: 'preworkout', color: 'var(--pink)',
    serving: '1 scoop', note: 'Caffeine + beta-alanine',
    macros: { kcal: 10 }, micros: { sodium: 150, magnesium: 50 },
  },
  {
    key: 'vitamins', label: 'Vitamins', icon: 'vitamins', color: 'var(--yellow)',
    serving: '1 tablet', note: 'Multivitamin',
    macros: {}, micros: { vitc: 40, vita: 600, vitd: 10, vitb12: 1, zinc: 8, iron: 8, calcium: 50 },
  },
  {
    key: 'omega3', label: 'Omega-3', icon: 'omega3', color: 'var(--orange)',
    serving: '1 softgel (1000mg)', note: 'Fish oil, EPA/DHA',
    macros: { kcal: 10, fat: 1 }, micros: {},
  },
  {
    key: 'bcaa', label: 'BCAA', icon: 'bcaa', color: 'var(--green)',
    serving: '1 scoop', note: 'Branched-chain aminos',
    macros: { kcal: 20, protein: 5 }, micros: { sodium: 50 },
  },
  {
    key: 'minerals', label: 'Minerals', icon: 'minerals', color: 'var(--purple)',
    serving: '1 tablet', note: 'Multimineral',
    macros: {}, micros: { calcium: 250, magnesium: 100, zinc: 10, iron: 5, potassium: 50 },
  },
  {
    key: 'ashwagandha', label: 'Ashwagandha', icon: 'ashwagandha', color: 'var(--green)',
    serving: '600 mg', note: 'Adaptogen, usually evening',
    macros: {}, micros: {},
  },
  {
    key: 'other', label: 'Other', icon: 'other', color: 'var(--ink-3)',
    serving: '1 dose', note: 'Anything else on the shelf',
    macros: {}, micros: {},
  },
];

export const suppByKey = k => SUPPLEMENTS.find(s => s.key === k) || SUPPLEMENTS[SUPPLEMENTS.length - 1];
