// Run: bun tests/rupee.test.js
//
// The rupee sign, and the daily-spark block. Two unrelated pieces of CSS share
// a suite because they share a failure mode: both are things that LOOK fine in
// the source and are wrong on the screen, and both have now been fixed twice.
//
// What this pins, and why each one was a real bug rather than a hypothetical:
//
//   1. TWO FACES, NOT ONE. The app has two font stacks that do not sit at the
//      same height — VT323 rests on the baseline and reaches ~700/1000 of the
//      em; Press Start 2P floats ~125 above it and reaches 1000. A single
//      U+20B9 face fits one stack and renders visibly short and low in the
//      other, which is exactly what the stat tiles were showing: a 29px sign
//      beside 36px digits, sitting five device-pixels lower. So RupeeFix is
//      drawn 0..700 for the body stack and RupeePixel 125..1000 for the pixel
//      stack, and each stack must LEAD with its own face — first matching
//      family wins per-codepoint, so a stack that lists the wrong one first
//      silently gets the wrong metrics with no error anywhere.
//
//   2. THE GLYPH IS NOT A LATIN R. The previous drawing had a stem running the
//      full height down the left side, a closed bowl and a leg — the
//      construction of R — and shipped, with a comment claiming it had been
//      checked against DejaVu's ₹. It had not been checked against the shape.
//      A real ₹ has NO left stem: it touches the left edge at exactly one
//      height, about halfway down, and nowhere else. That single property is
//      what this suite asserts, because it is the one that distinguishes the
//      two letters and it is cheap to state.
//
//   3. THE UNICODE-RANGE IS THE SAFETY. These faces contain one glyph. Without
//      `unicode-range: U+20B9` on each, listing them first in a stack would
//      hand the browser a face with no letters and every other character would
//      fall through to the next family — which works, but only by accident,
//      and stops working the moment a second glyph is added.
//
//   4. THE SPARK STACKS AND DOES NOT TRUNCATE. The block sat as one baseline
//      row of label | quote | attribution, so the quote was the only element
//      that could absorb the slack and it truncated with an ellipsis. A
//      truncated aphorism is not an aphorism. The fix is a right-aligned
//      column. `white-space: nowrap` on the quote is therefore the specific
//      regression to guard, along with the label ordering — the label is a
//      caption and belongs above the thing it captions, not to its left.
//
// This reads the generated CSS off disk rather than importing anything, which
// is the only way to test it: the font is generated by a python script that
// splices base64 into theme.css, and nothing in the JS bundle knows it exists.

import { readFileSync } from 'fs';

let pass = 0, fail = 0;
const bad = [];
const ok = (name, cond, got) => {
  if (cond) pass++;
  else { fail++; bad.push(name); console.log('FAIL', name, got === undefined ? '' : `— ${got}`); }
};

const theme = readFileSync(new URL('../src/theme.css', import.meta.url), 'utf8');
const arcade = readFileSync(new URL('../src/arcade.css', import.meta.url), 'utf8');
const hq = readFileSync(new URL('../src/tabs/HQ.jsx', import.meta.url), 'utf8');

// ---------------------------------------------------------------- 1. two faces

// Hand-typed literals, deliberately, rather than a loop over a FACES table
// read out of the CSS — a table-driven walk here would assert that the file
// agrees with itself, which it always does.
const faceBlocks = [...theme.matchAll(
  /@font-face\s*\{([^}]*)\}/g,
)].map(m => m[1]);

const byFamily = {};
for (const b of faceBlocks) {
  const fam = /font-family:\s*'([^']+)'/.exec(b);
  if (fam) byFamily[fam[1]] = b;
}

ok('RupeeFix is defined as an @font-face', !!byFamily.RupeeFix);
ok('RupeePixel is defined as an @font-face', !!byFamily.RupeePixel);
ok('and they are two distinct faces, not one aliased twice',
  byFamily.RupeeFix !== byFamily.RupeePixel);

for (const fam of ['RupeeFix', 'RupeePixel']) {
  const b = byFamily[fam] || '';
  ok(`${fam} is restricted to U+20B9`, /unicode-range:\s*U\+20B9\s*;/i.test(b), b.slice(0, 80));
  ok(`${fam} is inlined as base64, not a network URL`,
    /src:\s*url\(data:font\/ttf;base64,[A-Za-z0-9+/=]+\)/.test(b));
  ok(`${fam} declares format('truetype')`, /format\('truetype'\)/.test(b));
}

// The two payloads must actually differ. Generating one face and naming it
// twice would satisfy every assertion above and reproduce the original bug.
const b64 = fam => (/base64,([A-Za-z0-9+/=]+)\)/.exec(byFamily[fam] || '') || [])[1] || '';
ok('the two faces carry different font data',
  b64('RupeeFix').length > 100 && b64('RupeeFix') !== b64('RupeePixel'));

// -------------------------------------------------------------- 2. the stacks

const varOf = name => {
  const m = new RegExp(`--${name}:\\s*([^;]+);`).exec(theme);
  return m ? m[1].trim() : '';
};

const pixel = varOf('font-pixel');
const body = varOf('font-body');

ok('--font-pixel leads with RupeePixel', /^'RupeePixel'/.test(pixel), pixel);
ok('--font-pixel still falls back to Press Start 2P', /Press Start 2P/.test(pixel), pixel);
ok('--font-body leads with RupeeFix', /^'RupeeFix'/.test(body), body);
ok('--font-body still falls back to VT323', /VT323/.test(body), body);

// The specific crossed-wires failure: the lifted face in the baseline stack or
// vice versa. Stated as its own assertion because it is the one a careless
// find-and-replace produces.
ok('the pixel stack does not lead with the baseline face', !/^'RupeeFix'/.test(pixel), pixel);
ok('the body stack does not lead with the lifted face', !/^'RupeePixel'/.test(body), body);

// ----------------------------------------------------------- 3. the drawing

// Decode RupeeFix and read its contours back out of the TTF. This is a
// deliberate re-derivation from the shipped bytes rather than from the python
// source: the python source is what was wrong last time, and it was wrong in a
// way that reading it did not reveal.
function glyphBoxes(base64) {
  const buf = Buffer.from(base64, 'base64');
  const numTables = buf.readUInt16BE(4);
  const tables = {};
  for (let i = 0; i < numTables; i++) {
    const o = 12 + i * 16;
    tables[buf.toString('ascii', o, o + 4)] = { off: buf.readUInt32BE(o + 8) };
  }
  // glyf holds .notdef (empty) then rupee; loca gives the offsets. indexToLocFormat
  // lives at head+50.
  const long = buf.readInt16BE(tables.head.off + 50) === 1;
  const loca = i => (long
    ? buf.readUInt32BE(tables.loca.off + i * 4)
    : buf.readUInt16BE(tables.loca.off + i * 2) * 2);
  const g = tables.glyf.off + loca(1);
  const end = tables.glyf.off + loca(2);
  if (end <= g) return null;
  const nContours = buf.readInt16BE(g);
  return {
    nContours,
    xMin: buf.readInt16BE(g + 2),
    yMin: buf.readInt16BE(g + 4),
    xMax: buf.readInt16BE(g + 6),
    yMax: buf.readInt16BE(g + 8),
  };
}

const fix = glyphBoxes(b64('RupeeFix'));
const pix = glyphBoxes(b64('RupeePixel'));

ok('RupeeFix has a rupee glyph with outlines', !!fix && fix.nContours > 0, JSON.stringify(fix));
ok('RupeePixel has a rupee glyph with outlines', !!pix && pix.nContours > 0, JSON.stringify(pix));

// The measured metrics, as literals. 0..700 and 125..1000 are not arbitrary —
// they are what a screenshot of the live stat tiles measured at 2x — so they
// are typed out rather than computed from the file.
ok('RupeeFix sits on the baseline', fix && fix.yMin === 0, fix && String(fix.yMin));
ok('RupeeFix reaches 700, matching VT323 digits',
  fix && fix.yMax === 700, fix && String(fix.yMax));
ok('RupeePixel floats 125 above the baseline, matching Press Start 2P',
  pix && pix.yMin === 125, pix && String(pix.yMin));
ok('RupeePixel reaches the full em, matching Press Start 2P digits',
  pix && pix.yMax === 1000, pix && String(pix.yMax));
ok('the lifted face is the taller of the two',
  fix && pix && (pix.yMax - pix.yMin) > (fix.yMax - fix.yMin));

// The R test. Rasterise the drawing from the ART grid the script ships and
// check the left column is lit on exactly one row. An R lights it on all of
// them; that is the whole difference.
const script = readFileSync(new URL('../scripts/make-rupee-font.py', import.meta.url), 'utf8');
const artBlock = /ART = \[([^\]]*)\]/.exec(script);
ok('the drawing is present in the generator as ASCII art', !!artBlock);
const ART = artBlock ? [...artBlock[1].matchAll(/'([.#]+)'/g)].map(m => m[1]) : [];

ok('the drawing is a 7x7 grid', ART.length === 7 && ART.every(r => r.length === 7),
  `${ART.length} rows`);

// The two full-width bars reach column 0 by definition, so they are excluded:
// the question is whether anything ELSE runs down the left side. In an R that
// is the stem and it is every remaining row. In a ₹ it is the bulge and it is
// exactly one.
const leftRows = ART
  .map((r, i) => (r[0] === '#' && r !== '#######' ? i : -1))
  .filter(i => i >= 0);
ok('outside the two bars, the left edge is touched on exactly one row — this is not a Latin R',
  leftRows.length === 1, `rows ${leftRows.join(',')}`);
ok('and that row is around the middle of the glyph, where the bulge is',
  leftRows[0] >= 3 && leftRows[0] <= 5, String(leftRows[0]));

// The two horizontal bars. A ₹ has two full-width bars; an R has none.
const fullRows = ART.map((r, i) => (r === '#######' ? i : -1)).filter(i => i >= 0);
ok('there are exactly two full-width bars', fullRows.length === 2, `rows ${fullRows.join(',')}`);
ok('the bars are the top row and the middle-upper row',
  fullRows[0] === 0 && fullRows[1] === 2, fullRows.join(','));

// The descending leg must be a connected region. Corner-touching steps are
// legally droppable by a rasteriser and came out as detached dots at 15px.
let connected = true;
for (let r = 3; r < ART.length; r++) {
  const a = ART[r - 1], b = ART[r];
  let shared = 0;
  for (let c = 0; c < 7; c++) if (a[c] === '#' && b[c] === '#') shared++;
  if (shared < 1) connected = false;
}
ok('every step of the descending stroke shares a full pixel edge with the next',
  connected);

// ------------------------------------------------------------- 4. daily spark

const sparkRule = (/\.hero-spark\s*\{([^}]*)\}/.exec(arcade) || [])[1] || '';
const qRule = (/\.hero-spark \.hs-q\s*\{([^}]*)\}/s.exec(arcade) || [])[1] || '';
const labelRule = (/\.hero-spark \.hs-label\s*\{([^}]*)\}/.exec(arcade) || [])[1] || '';
const aRule = (/\.hero-spark \.hs-a\s*\{([^}]*)\}/.exec(arcade) || [])[1] || '';

ok('.hero-spark exists', !!sparkRule);
ok('the spark stacks in a column', /flex-direction:\s*column/.test(sparkRule), sparkRule);
ok('and is right-aligned against the hero edge it hangs off',
  /text-align:\s*right/.test(sparkRule) && /align-items:\s*flex-end/.test(sparkRule), sparkRule);
ok('it still hangs in the hero bottom-right corner',
  /position:\s*absolute/.test(sparkRule) && /bottom:/.test(sparkRule) && /right:/.test(sparkRule));
ok('above the hero scrim and text', /z-index:\s*3/.test(sparkRule));

// The regression, named: the quote must not be a single truncating line.
ok('the quote does not truncate to one line', !/white-space:\s*nowrap/.test(qRule), qRule);
ok('the quote does not use an ellipsis', !/text-overflow/.test(qRule), qRule);
ok('the quote is capped at two lines so it cannot grow up through the greeting',
  /-webkit-line-clamp:\s*2/.test(qRule), qRule);
ok('the cap is a clamp on a wrapped block, not a fixed height',
  /-webkit-box-orient:\s*vertical/.test(qRule) && !/(^|[;\s])height:/.test(qRule), qRule);

ok('the label is drawn in the pixel font', /var\(--font-pixel\)/.test(labelRule), labelRule);
ok('the label is the yellow accent', /var\(--yellow\)/.test(labelRule), labelRule);
ok('the attribution is muted, not the same weight as the quote',
  /var\(--ink-2\)/.test(aRule), aRule);
ok('the quote is the largest of the three',
  parseFloat(/font-size:\s*([\d.]+)px/.exec(qRule)[1])
  > parseFloat(/font-size:\s*([\d.]+)px/.exec(labelRule)[1]));

// Source order is what puts the caption above the quote, since the block is a
// plain column with no explicit `order`. Asserted on the JSX, not the CSS.
const iLabel = hq.indexOf('hs-label');
const iQ = hq.indexOf('hs-q');
const iA = hq.indexOf('hs-a');
ok('the JSX orders label, then quote, then attribution',
  iLabel > 0 && iLabel < iQ && iQ < iA, `${iLabel}/${iQ}/${iA}`);
ok('no explicit order property fights the source order',
  !/(^|[;\s])order:\s*\d/.test(sparkRule + qRule + labelRule + aRule));

// The phone fallback drops the corner treatment; the clamp goes with it,
// because in the flow the block is free to grow downward.
const mobile = (/@media \(max-width: 760px\) \{([\s\S]*?)\n\}/.exec(arcade) || [])[1] || '';
ok('the phone layout returns the spark to the flow',
  /\.hero-spark\s*\{[^}]*position:\s*static/.test(mobile), mobile.slice(0, 120));
ok('and lifts the two-line cap there',
  /\.hero-spark \.hs-q\s*\{[^}]*-webkit-line-clamp:\s*none/.test(mobile));

console.log(`\n${pass}/${pass + fail} passing`);
if (fail) { console.log('\nfailing:\n  ' + bad.join('\n  ')); process.exit(1); }
